#!/bin/bash

set -e
set -x

DATA_GENERATOR_PROGRAM="${BUILD_ROOT}/${CONFIGURATION}/${DATABASE_GENERATOR}"

if [ -f ${GENERATED_DATABASE} ]; then
  rm -rf ${GENERATED_DATABASE}
  fi

  ${DATA_GENERATOR_PROGRAM} ${GENERATED_DATABASE}

# Copy the generated database into the app resources folder
# This cannot be done in the "Copy Phase" because Xcode does
# not support copying files that are generated by a script
#
# Also, Sqlite generates *-shm and a *-wal files.  These files
# must also be copied into the app in order for the DB to 
# be loadable on a real device (for some reason the app can load
# on the simulator without these, though).  Anyways, that's what
# the wildcard is there for in the statement below.
cp ${GENERATED_DATABASE}* ${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/

